server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Use the Astro 404 page
    error_page 404 /404.html;

    # Internal route to serve the 404 page
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Normal routes: if the file does not exist, throw 404
    location / {
        try_files $uri $uri/ =404;
    }
}