services:
  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile.dev
    container_name: ania_server_dev
    image: ania_server:dev
    env_file:
      - .env
    volumes:
      - ../server:/app

  web_admin:
    build:
      context: ..
      dockerfile: docker/admin-website/Dockerfile.dev
    container_name: ania_web_admin_dev
    image: ania_web_admin:dev
    volumes:
      - ../admin-website:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_NODE_ENV=development

  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
      target: dev
    image: ania_web:dev
    container_name: ania_web_dev
    volumes:
      - ../client:/app
      - /app/node_modules
