FROM oven/bun:1.3-alpine

WORKDIR /workspace

ENV NODE_ENV=development

CMD ["sh", "-lc", "apk add --no-cache nodejs npm && npm install -g pnpm@11.4.0 && pnpm install && bun run --cwd admin-website dev"]
